# Generated by Django 5.0.6 on 2025-08-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_credit',
            field=models.CharField(default='Image by Author', max_length=255),
        ),
    ]
