# Generated by Django 5.0.6 on 2025-08-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_image_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='views',
        ),
    ]
